# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "test-app"
client_id = "1c2bee04dc0a576ceb4a0212b71026b8"
application_url = "https://ease-namibia-structured-kills.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://ease-namibia-structured-kills.trycloudflare.com/auth/callback",
  "https://ease-namibia-structured-kills.trycloudflare.com/auth/shopify/callback",
  "https://ease-namibia-structured-kills.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "longpn-store-app.myshopify.com"
